Add token details
MapColonies/nginx-s3-gateway pull request #11
Opened 2023-05-18 13:44 UTC by netanelC

This PR adds the JWT parser and makes the names shorter

2023-06-08 04:19 UTC, EllaMartirosyan requested changes
This branch is not synced with the master, please merge it, we also need this changes

2023-06-27 19:53 UTC, EllaMartirosyan approved these changes

2023-06-29 16:21 UTC, alebinson approved these changes
gr8!

2023-07-04 13:10 UTC, alebinson requested changes

2023-07-04 13:10 UTC, alebinson commented on helm/values.yaml
> +  noCache: true
think, by default should be **false**

2023-07-04 13:51 UTC, EllaMartirosyan commented on helm/values.yaml
> +  noCache: true
I know, I'm still testing this feature...

2023-07-10 09:35 UTC, netanelC reviewed
If configmap conf is empty, don't point to that configmap. Instead, you can do an if statement to not point to the empty configmap. @EllaMartirosyan

2023-07-17 08:36 UTC, alebinson approved these changes
gr8!

2023-07-17 08:42 UTC, merged